### ISSUE TITLE
Publish 0.1.4 on npm

### ISSUE THREAD

**Issue by QuentinFchx** [tony-o/node-optional#8]
The current npm version is 0.1.3 with a "v" in the `version` prop of the `package.json` (`v0.1.3`).
It seems to cause issue with yarn:
`error "imagemin#optional" is wrong version: expected "0.1.3", got "v0.1.3"`

Could you publish `0.1.4` that have this fixed?

**Comment by jeffcarbs** [comment]
Just ran into the same issue - would also love to get version `0.1.4` onto npm. Thanks!

**Comment by tony-o** [comment]
Check it out - should be published now.
